[package]
name = "nine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bench]]
name = "nine_bench"
harness = false

[dependencies]

[dev-dependencies]
bencher = "0.1.4"
